apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    version: preview
  ports:
    - port: 80
      targetPort: 80
