apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: canary-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  index.html: |
    <h1>Canary deployments, inceasing the pods !!!</h1>