apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: wave
  annotations:
     argocd.argoproj.io/hook: Sync 
#    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: argoproj/rollouts-demo:blue #nginx:perl #argoproj/rollouts-demo:green #blue #nginx:perl
        ports:
        - containerPort: 80 #8080
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-html
